# ==============================================================================
# ACTIONS DU MODE SPÉCIAL (settings/actions/hotkeys.toml)
# ==============================================================================
# Chaque action définit un tableau 'commands = [ ... ]' contenant ses commandes.
# Les paramètres peuvent être passés sous forme d'array 'params = [...]' pour
# une structure claire et compacte.

[[actions]]
name = "select all"
description = ""
modes = ["special"]
trigger = "a"
commands = [
    { type = "hotkey", params = ["ctrl", "a"] }
]

[[actions]]
name = "annuler"
description = ""
modes = ["special"]
trigger = "z"
commands = [
    { type = "hotkey", params = ["ctrl", "z"] }
]

[[actions]]
name = "copy"
description = ""
modes = ["special"]
trigger = "c"
commands = [
    { type = "hotkey", params = ["ctrl", "c"] }
]

[[actions]]
name = "cut"
description = ""
modes = ["special"]
trigger = "x"
commands = [
    { type = "hotkey", params = ["ctrl", "x"] }
]

[[actions]]
name = "paste"
description = ""
modes = ["special"]
trigger = "v"
commands = [
    { type = "hotkey", params = ["ctrl", "v"] }
]

[[actions]]
name = "minimize"
description = ""
modes = ["special"]
trigger = ""
commands = [
    { type = "hotkey", params = ["win", "down"] }
]

[[actions]]
name = "maximize"
description = ""
modes = ["special"]
trigger = ""
commands = [
    { type = "hotkey", params = ["win", "up"] }
]

[[actions]]
name = "presse papiers"
description = ""
modes = ["special"]
trigger = ""
commands = [
    { type = "hotkey", params = ["win", "v"] }
]

[[actions]]
name = "renommer"
description = "Renommer l'élément sélectionné"
modes = ["special"]
trigger = ""
commands = [
    { type = "hotkey", params = ["f2"] }
]

[[actions]]
name = "bureau"
description = "aller sur le bureau"
modes = ["special"]
trigger = "b"
commands = [
    { type = "hotkey", params = ["win", "d"] }
]

[[actions]]
name = "programme suivant"
description = "prog suivant"
modes = ["special"]
trigger = ":"
commands = [
    { type = "hotkey", params = ["alt", "escape"] }
]

[[actions]]
name = "liste"
description = "liste"
modes = ["special"]
trigger = "!"
commands = [
    { type = "hotkey", params = ["win", "tab"] }
]


