[[actions]]
name = "Clic Gauche"
description = "Simule un clic du bouton gauche"
modes = ["special"]
trigger = ";"
commands = [
    { type = "click", params = ["left"] }
]

[[actions]]
name = "Clic Milieu"
description = "Simule un clic molette (bouton du milieu)"
modes = ["special"]
trigger = ":"
commands = [
    { type = "middle_click" }
]

[[actions]]
name = "Vitesse Souris / Trackpad"
description = "Bascule la vitesse du pointeur entre rapide (18) et normale (10)"
modes = ["special"]
trigger = "s"
commands = [
    { type = "mouse_speed", speed = 100, toggle = true }
]

[[actions]]
name = "Drag & Drop"
description = "Bascule le maintien et le relâchement du clic gauche (glisser-déposer)"
modes = ["special"]
trigger = ","
toggle = true
states = [
    { name = "Maintien Clic (Drag)", commands = [{ type = "mouse_down", button = "left" }] },
    { name = "Relâchement Clic (Drop)", commands = [{ type = "mouse_up", button = "left" }] }
]

[[actions]]
name = "Molette Haut (Scroll Up)"
description = "Défilement vertical vers le haut"
modes = ["special"]
trigger = "y"
commands = [
    { type = "scroll", delta = 3 }
]

[[actions]]
name = "Molette Bas (Scroll Down)"
description = "Défilement vertical vers le bas"
modes = ["special"]
trigger = "u"
commands = [
    { type = "scroll", delta = -3 }
]


