# Action : Bascule État Exemple
name = "Toggle Mode Spécial/Normal"
description = "Bascule entre le mode normal et le mode spécial."

# Disponible dans les modes normal et special
modes = ["normal", "special"]
trigger = "!"

# Toggle d'états
toggle = true

[states.0]
name = "Vers Spécial"
[[states.0.commands]]
type = "mode"
target = "special"

[states.1]
name = "Vers Normal"
[[states.1.commands]]
type = "mode"
target = "normal"
