# ==============================================================================
# ACTION TOGGLE MODE (settings/actions/toggle_mode.toml)
# ==============================================================================

[[actions]]
name = "Toggle Mode Spécial/Normal"
description = "Bascule entre le mode normal et le mode spécial."
modes = ["all"]
trigger = "0"
commands = [{ type = "mode", params = { target = "toggle", toggle_with = "special" } }]


# [[actions]]
# name = "Toggle Mode Spécial/Grid"
# description = ""
# modes = ["special", "grid"]
# trigger = ""
# toggle = true
# states = [
#    { name = "vers grid", commands = [{ type = "mode", params = ["grid"] }] },
#    { name = "vers special", commands = [{ type = "mode", params = ["special"] }] }
# ]